apiVersion: v1
kind: Service
metadata:
  name: dispatcher
spec:
  type: NodePort

  # clusterIP: 162.38.112.41
  selector:
    app: dispatcher
  ports:
    - port: 8080
  # externalIPs: 
  #   - 162.38.112.41