- hosts: control
  become: yes
  become_user: root
  roles:
    - docker
    - kubeadm
    - control/init
    - deploy
- hosts : worker
  become: yes
  become_user: root
  roles:
    - docker
    - kubeadm
    - worker/connect
