apiVersion: apps/v1
kind: Deployement
metadata:
  name: provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider-subject
  template:
    metadata:
      labels:
        app: provider-subject
    spec:
      containers:
        - name: provider
          image: registry.hub.docker.com/fteychene/cloud-cadavre-exquis-provider
          ports:
            - container-port: 80
          env:
            - WORD_TYPE: SUBJECT
      restartPolicy: OnFailure
