- name: Configure the control plane
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_init
- name: Copy kube config
  shell: |
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Tigera
  when: kubeadm_init
  shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
  register: tigera_install
- name: Install Calico
  when: tigera_install
  shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
  register: calico_install

- name: Wait for pods to be up
  when: calico_install
  shell: kubectl wait --namespace=calico-system --for=condition=Ready pods --selector tier=control-plane --timeout=600s
  register: kubeadm_started

- name: Taint node
  when: kubeadm_started
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  register: kubeadem_finished

- name: Generate join command
  when: kubeadem_finished
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Set join command
  set_fact:
    join_command: "{{ join_command.stdout }}"