- name: Check that docker binary exists
  shell:
  register: is_docker_exist
  ignore_errors: true

- name: Configure the control plane
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16
  register: kubeadm_init
  ignore_errors: true

- name: Copy kube config
  when: kubeadm_init.rc == 0
  shell: |
    mkdir -p /root/.kube
    cp /etc/kubernetes/admin.conf /root/.kube/config
    chown $(id -u):$(id -g) $HOME/.kube/config

- name: Install Tigera
  when: kubeadm_init.rc == 0
  shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/tigera-operator.yaml
  register: tigera_install
- name: Install Calico
  when: kubeadm_init.rc == 0
  shell: kubectl create -f https://projectcalico.docs.tigera.io/manifests/custom-resources.yaml
  register: calico_install

- name: Wait for pods to be up
  when: kubeadm_init.rc == 0
  shell: kubectl wait --for=condition=Ready nodes --all --timeout=600s
  register: kubeadm_started

- name: Taint node
  when: kubeadm_init.rc == 0
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
  register: kubeadem_finished

- name: Generate join command
  when: kubeadem_finished
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Set join command
  set_fact:
    control_join_command: "{{ join_command.stdout }}"
